- include: centos.yml
  when: ansible_distribution == 'CentOS'

- include: debian.yml
  when: ansible_distribution == 'Debian'

- name: "Download the DynamoDB local jar"
  get_url:
    url: "{{ dynamodb_source_url }}"
    sha256sum: "{{ dynamodb_sha }}"
    dest: /tmp
  notify:
    - Restart DynamoDB
  register: dynamodb_download
  tags:
    - dynamodb
    - files
    - pkgs

- name: "Install DynamoDB in {{ dynamodb_install_dir }}"
  shell: |
    mkdir dynamodb_local_{{ dynamodb_version }} && \
    cd dynamodb_local_{{ dynamodb_version }} && \
    tar -zxvf ../dynamodb_local_{{ dynamodb_version }}.tar.gz && \
    mkdir -p "{{ dynamodb_install_dir }}" && \
    rsync -av ./ "{{ dynamodb_install_dir }}" && \
    cd .. && \
    rm -rf dynamodb_local_{{ dynamodb_version }}/
  args:
    chdir: /tmp
  when: dynamodb_download.changed
  tags:
    - dynamodb
    - files
    - pkgs

- name: "Enable log rotation"
  template:
    src: dynamodb_local_log_rotate.conf
    dest: "{{ dynamodb_log_rotate_file }}"
    mode: 0644
  tags:
    - dynamodb
    - files

- name: "Drop an init.d file for DynamoDB"
  template:
    src: dynamodb.init.sh
    dest: "{{ dynamodb_init_script }}"
    mode: 0700
    owner: root
    group: root
  notify:
    - Restart DynamoDB
  tags:
    - dynamodb
    - files

- name: "Make sure DynamoDB local development is running"
  service:
    name: dynamodb
    state: running
    enabled: yes
    runlevel: 5
    pattern: "DynamoDBLocal.jar"
  tags:
    - dynamodb
    - services
